<a href="https://colab.research.google.com/github/123Prostab/Practice-ML-DL/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
The numpy array object
1. high level number objects : integers , floating points
2. contains lists and dictionary
Numpy provides :
1. extension package to python multidimensional array
2. closer to hardware
3. designed to scientific computation
4. also known as array oriented computing

In [ ]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
l = range(1000)
%timeit [i**2 for i in l]

1000 loops, best of 5: 265 µs per loop


In [ ]:
a = np.arange(1000)
%timeit a ** 2

The slowest run took 35.31 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 1.46 µs per loop


In [ ]:
#manual construction of array
a = np.array([0,1,2,3])
print(a ) 

[0 1 2 3]


In [ ]:
a.ndim

1

In [ ]:
a.shape

(4,)

In [ ]:
len(a)

4

In [ ]:
b = np.array([[0,1,2],[3,4,5]])
print(b)

[[0 1 2]
 [3 4 5]]


In [ ]:
b.shape

(2, 3)

In [ ]:
b.ndim

2

In [ ]:
len(b)

2

In [ ]:
c = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
c.ndim


3

In [ ]:
c.shape

(2, 2, 2)

In [ ]:
len(c)

2

In [ ]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [ ]:
a = np.linspace(0,1,6)
a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [ ]:
#common array
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
b = np.zeros((3,3))
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
c = np.eye(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
c = np.eye(3,2)
c

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [ ]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
np.diag(a)

array([1, 2, 3, 4])

In [ ]:
a = np.random.rand(4)
a

array([0.83684772, 0.7615564 , 0.41082851, 0.39444004])

In [ ]:
a = np.random.randn(4)
a

array([ 1.53603675, -0.18082418, -0.54507989, -0.75969338])

In [ ]:
a = np.arange(10)
a.dtype

dtype('int64')

In [ ]:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
d = np.array([1+2j,2+4j])
print(d.dtype)

complex128


In [ ]:
c = np.array(["Ram","Robert","Rahim"])
print(c.dtype)

<U6


In [ ]:
b = np.array([True,False,True,False])
print(b.dtype)

bool


In [ ]:
a = np.arange(10)
print(a[5])

5


In [ ]:
a = np.diag([1,2,3])
a[2][2] = 5
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 5]])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2]

array([1, 3, 5, 7])

In [ ]:
b = np.arange(5)
a[5:] = b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b


array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,b)


True

In [ ]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [ ]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
c = a[::2].copy()
c

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a,c)

False

In [ ]:
c[0] = 52
c


array([52,  2,  4,  6,  8])

In [ ]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#fancy indexing
a = np.random.randint(0,20,15)
a

array([16,  5, 13, 17, 13, 17,  9,  6, 16, 15,  9,  1, 10, 14,  3])

In [ ]:
mask = (a % 2 == 0)

In [ ]:
extract_from_a = a[mask]
extract_from_a

array([16,  6, 16, 10, 14])

In [ ]:
a[mask] = -1
a

array([-1,  5, 13, 17, 13, 17,  9, -1, -1, 15,  9,  1, -1, -1,  3])

In [ ]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
a[[2,3,2,4,2]]

array([20, 30, 20, 40, 20])

In [ ]:
a[[9,7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])