<a href="https://colab.research.google.com/github/123Prostab/Practice-ML-DL/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a + 1

array([2, 3, 4, 5])

In [3]:
a ** 2

array([ 1,  4,  9, 16])

In [7]:
b = np.ones((4,)) + 1 
a - b


array([-1.,  0.,  1.,  2.])

In [8]:
a * b

array([2., 4., 6., 8.])

In [10]:
c = np.diag([1,2,3,4])
print(c * c)
print("***************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
***************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [11]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
a == b


array([False,  True, False,  True])

In [12]:
a > b

array([False, False,  True, False])

In [13]:
a = np.array([1,2,3,4])
b = np.array([5,2,2,4])
c = np.array([1,2,3,4])
np.array_equal(a,b)

False

In [14]:
np.array_equal(a,c)

True

In [15]:
a = np.array([1,1,0,0],dtype=bool)
b = np.array([1,1,0,0],dtype=bool)
np.logical_or(a,b)

array([ True,  True, False, False])

In [16]:
np.logical_and(a,b)

array([ True,  True, False, False])

In [17]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [18]:
np.log(a)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [19]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [20]:
a = np.arange(4)
a + np.array([1,2])

ValueError: ignored

In [21]:
x = np.array([1,2,3,4])
np.sum(x)


10

In [23]:
x = np.array([[1,1],[2,2]])
x

array([[1, 1],
       [2, 2]])

In [24]:
x.sum(axis = 0)


array([3, 3])

In [25]:
x.sum(axis = 1)

array([2, 4])

In [26]:
x = np.array([1,3,2])

In [27]:
x.min()

1

In [28]:
x.max()

3

In [29]:
x.argmax()

1

In [30]:
x.argmin()

0

In [32]:
np.all([True,True,False])

False

In [33]:
np.any([True,False,False])


True

In [35]:
a = np.zeros((50,50))
np.any(a != 0)


False

In [36]:
np.all(a == a )

True

In [37]:
a = np.array([1,2,3,2])
b = np.array([2,2,3,2])
c = np.array([6,4,4,5])
((a <= b) & (b <= c)).all()

True

In [38]:
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()

1.75

In [39]:
np.median(x)

1.5

In [40]:
np.median(y,axis = 1)

array([2., 5.])

In [41]:
x.std()

0.82915619758885

In [43]:
data = np.loadtxt('populations.txt')

In [44]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [45]:
year,hares,lynxes, carrots = data.T
year

array([1900., 1901., 1902., 1903., 1904., 1905., 1906., 1907., 1908.,
       1909., 1910., 1911., 1912., 1913., 1914., 1915., 1916., 1917.,
       1918., 1919., 1920.])

In [46]:
populations = data[:,1:]
populations

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [47]:
populations.std(axis = 0)


array([20897.90645809, 16254.59153691,  3322.50622558])

In [48]:
np.argmax(populations,axis = 1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [50]:
a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print("***************")
a = a.T
print(a)

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
***************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [51]:
b = np.array([0,1,2])
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [53]:
a = np.arange(0,40,10)
a.shape

(4,)

In [54]:
a = a [:,np.newaxis]
a.shape

(4, 1)

In [55]:
a

array([[ 0],
       [10],
       [20],
       [30]])

In [56]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [57]:
a = np.array([[1,2,3],[4,5,6]])
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [59]:
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [60]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [61]:
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [62]:
b = a.ravel()
print(b)

[1 2 3 4 5 6]


In [63]:
b = b.reshape((2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])